# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'lessons'
version: '1.0.0'
config-version: 2

# Określa, który "profil" dbt będzie używany w projekcie.
# Profile definiują połączenia do baz danych i inne ustawienia środowiskowe.
profile: 'lessons'

# Określają, w których folderach projektu dbt znajdują się modele SQL,
# analizy, testy, dane początkowe (seeds), makra i migawki (snapshots).
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # Określa folder, w którym dbt przechowuje skompilowane pliki SQL.
clean-targets:         # Określa foldery, które zostaną usunięte podczas czyszczenia (dbt clean).
  - "target"
  - "dbt_packages"


# Konfiguruje modele dbt, określając ich materializację (np. jako tabele w bazie danych),
# jak również ustawienia dotyczące dokumentacji, takie jak zapisywanie opisów kolumn do BigQuery.
# Dodatkowo, w tej sekcji możemy określić czas wygaśnięcia tabel.
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  lessons:
    +materialized: table # Default all SQL models to be materialised as tables
    +persist_docs: # Writes all of our column descriptions into BigQuery!
      relation: true
      columns: true
    # Table deletes 168 hours (7 days) after creation
    # Table deletes 8760 hours (1 rok) after creation
    +hours_to_expiration: 8760

# Konfiguruje testy dbt, określając domyślny poziom powagi dla testów w projekcie.
tests:
  lessons:
    +severity: warn # Wszystkie testy w naszym projekcie lekcji domyślnie wyświetlają ostrzeżenie (nie error)